In [3]:
import numpy as np

In [5]:
# create array

var1 =[1,2,3,4]
print(var1)
np.array(var1)

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [7]:
print(var1)
array = np.array(var1)
array

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [13]:
var2 =[1,3,4,8]
print(var2)
np.array(var2)

[1, 3, 4, 8]


array([1, 3, 4, 8])

In [21]:
var1 = np.array(['x','y','z'])
print(var1)
array = np.array(var1)
array

['x' 'y' 'z']


array(['x', 'y', 'z'], dtype='<U1')

In [23]:
var1 = np.array(['A', 'b','c','d',2])
print(var1)

['A' 'b' 'c' 'd' '2']


## Random

In [26]:
random_numbers = np.random.random(size=20)
print(random_numbers)

[0.50941127 0.29882011 0.48368097 0.72916573 0.07954215 0.24473732
 0.55275282 0.54287999 0.02479085 0.37498506 0.44866119 0.5723813
 0.8874069  0.43861353 0.2586565  0.40437664 0.19104066 0.9640829
 0.93849123 0.97711373]


In [30]:
random = np.random.rand(2,3)
print(random)


[[0.35918863 0.15743516 0.14555628]
 [0.88935609 0.43650176 0.82708668]]


In [39]:
random = np.random.rand(3,5)
print(random)

[[0.67817402 0.51077887 0.37931717 0.53325956 0.68920606]
 [0.2805925  0.0684553  0.05520094 0.05370239 0.84346167]
 [0.09553045 0.39077447 0.1212698  0.39795781 0.92879613]]


In [41]:
random = np.random.rand(11,3)
print(random)

[[0.56727436 0.07118452 0.39519511]
 [0.74892843 0.61753929 0.17335553]
 [0.82741566 0.30213315 0.13877033]
 [0.61974835 0.48082198 0.96351989]
 [0.7258234  0.67575865 0.60913327]
 [0.73717893 0.09462829 0.89489902]
 [0.97011484 0.71875768 0.83423871]
 [0.21948554 0.34974667 0.80343678]
 [0.41012014 0.70731026 0.87591662]
 [0.07298505 0.4507222  0.18987971]
 [0.07158861 0.9375829  0.37983143]]


In [49]:
random = np.random.rand(3,10)
print(random)

[[0.71956268 0.82554599 0.98995378 0.9978524  0.86455918 0.79335895
  0.47658225 0.35783643 0.13027552 0.16664924]
 [0.09116421 0.05067048 0.88195674 0.58389403 0.48301106 0.4476105
  0.15939232 0.10146273 0.46228894 0.46731675]
 [0.19114853 0.07661685 0.35397808 0.1048075  0.42398549 0.50643643
  0.9386675  0.00212619 0.03878932 0.01220899]]


In [55]:
random = np.random.rand(5,2)
print(random)

[[0.02924316 0.89888607]
 [0.50518849 0.64857843]
 [0.71395928 0.83568862]
 [0.38649008 0.5879999 ]
 [0.68332642 0.56513809]]


In [53]:
random = np.random.rand(4,2)
print(random)

[[0.59745172 0.22962222]
 [0.69967678 0.12409607]
 [0.27455537 0.86882741]
 [0.27740112 0.3407112 ]]


In [57]:
random = np.random.randn(2,3)
print(random)

[[ 1.65989787 -1.29467061  0.39327211]
 [-0.12078723  0.95722308  0.42252862]]


In [59]:
random = np.random.randn(3,5)
print(random)

[[-0.7039122   0.72745429 -1.57100536  1.3169273   0.14384114]
 [-0.51687288  0.06503144 -0.6237025   1.72619796  1.06288334]
 [-1.09445708 -0.53920016 -0.87802349  0.62617234  1.32855907]]


In [61]:
random = np.random.rand(5,6)
print(random)

[[0.56378172 0.25852191 0.24710746 0.92352256 0.99065382 0.90555252]
 [0.10423052 0.56355254 0.77953065 0.47051733 0.38777224 0.47500096]
 [0.96170643 0.53280563 0.23628652 0.02479252 0.88243963 0.73765172]
 [0.32644126 0.97228435 0.75559656 0.98979508 0.65010577 0.24606051]
 [0.83631456 0.89471994 0.08703189 0.97820487 0.64658266 0.49349699]]


In [63]:
random = np.random.randint(2,10)
print(random)

5


In [65]:
random = np.random.randint(10,100,10)
print(random)

[44 99 37 35 26 76 51 97 79 14]


In [67]:
random = np.random.randint(10,50,10)
print(random)

[28 19 46 43 35 28 45 35 33 41]


## Arange(imp)

In [78]:
even_nums = np.arange(start = 10, stop = 100, step = 2)
print(even_nums)
type(even_nums)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


numpy.ndarray

In [80]:
odd_nums = np.arange(start = 20, stop = 200, step = 2)
print(odd_nums)
type(odd_nums)

[ 20  22  24  26  28  30  32  34  36  38  40  42  44  46  48  50  52  54
  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84  86  88  90
  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120 122 124 126
 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156 158 160 162
 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192 194 196 198]


numpy.ndarray

## linspace

In [82]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [86]:
np.linspace(1,100,6)

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [90]:
np.linspace(1,100,3)

array([  1. ,  50.5, 100. ])

In [92]:
random = np.linspace(10,50,10)
print(random)

[10.         14.44444444 18.88888889 23.33333333 27.77777778 32.22222222
 36.66666667 41.11111111 45.55555556 50.        ]


In [94]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [100]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [102]:
np.ones(10),np.zeros(10)

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [120]:
np.empty((2,3),dtype='int')

array([[         0, 1072693248,          0],
       [1078542336,          0, 1079574528]])

In [126]:
np.empty((4,3),dtype='float')

array([[1.01855798e-312, 1.10343781e-312, 1.01855798e-312],
       [9.54898106e-313, 1.01855798e-312, 1.03977794e-312],
       [1.23075756e-312, 1.10343781e-312, 1.12465777e-312],
       [9.76118064e-313, 1.10343781e-312, 1.90979621e-312]])

In [124]:
np.empty((1,3),dtype='object')

array([[None, None, None]], dtype=object)

In [134]:
np.full((3,3), fill_value = 11)


array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

In [136]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [140]:
np.full((4,5), fill_value = 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [142]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [146]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [150]:
np.eye(5,5,0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [152]:
np.eye(5,5,3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [154]:
np.eye(5,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [156]:
np.eye(4,4,-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [158]:
np.eye(3,3,0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [162]:
np.eye(6,6,-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

## Shape

In [168]:
a = np.array(((1,2,3),(2,3,4)))
#a.ndim

In [166]:
row,col = a.shape

print(f'No of rows: {row}\nNo of columns: {col}')

No of rows: 2
No of columns: 3


In [174]:
a = np.array(((1,2,3),(2,5,6),(2,3,4)))
a

array([[1, 2, 3],
       [2, 5, 6],
       [2, 3, 4]])

In [ ]:
row,col = a.shape
size = a.size

print(f'No of rows: {row}\nNo of columns: {col}')
print(f'size of array: {size})

In [11]:
data_scientists = np.array([("Charles", 18),("Logan" ,20),("Jessica" ,34)])
print("last element: ",data_scientists[-1])

last element:  ['Jessica' '34']


In [13]:
data_scientists = np.array([("Charles", 18),("Logan" ,20),("Jessica" ,34)])
print("element at index position 1: ",data_scientists[1])

element at index position 1:  ['Logan' '20']


In [15]:
data_scientists = np.array([("Charles", 18),("Logan" ,20),("Jessica" ,34)])
data_scientists[0][1]

'18'

In [ ]:
import matplotlib.pyplot as plt

im = plt.imread('download.png')

im.shape,im.size

In [27]:
num_array = np.array([1,2,3,4,5])
print('update_array:', num_array*2)

update_array: [ 2  4  6  8 10]


In [29]:
m1 = np.array([[1,0,2],[4,-2,3]])
m2 = np.array([[4,0,1],[2,3,0]])
prod = m1*m2
print('element-wise multiplication:\n',prod)

element-wise multiplication:
 [[ 4  0  2]
 [ 8 -6  0]]


In [31]:
m1 = np.array([[1,0,2],[4,-2,3]])
m2 = np.array([[4,0],[2,3],[1,4]])
multi = m1.dot(m2)
print('matrix multiplication:\n',multi)

matrix multiplication:
 [[ 6  8]
 [15  6]]


In [33]:
salary = np.array([10000, 2000, 45000, 980000, 1000, 75500])
print("minimum salary in array: ",salary.min())

minimum salary in array:  1000


In [35]:
salary = np.array([10000, 2000, 45000, 980000, 1000, 75500])
print("maximum salary in array: ",salary.max())

maximum salary in array:  980000


In [37]:
salary = np.array([10000, 2000, 45000, 980000, 1000, 75500])
print("variance is salaries: ",salary.var())

variance is salaries:  126930534722.22223


In [39]:
salary = np.array([10000, 2000, 45000, 980000, 1000, 75500])
print("standard deviation in employee salaries: ",salary.std())

standard deviation in employee salaries:  356273.1181582779


In [41]:
sq_sides = np.array([20, 35, 40, 60, 75])
print("Area of squares: ",np.square(sq_sides))

Area of squares:  [ 400 1225 1600 3600 5625]


In [43]:
cube_sides = np.array([20, 35, 40, 60, 75])
print("volume of cubes: ",np.power(cube_sides,3))

volume of cubes:  [  8000  42875  64000 216000 421875]


In [47]:
data_scientists = np.array([("Charles", 18),("Logan", 20),("Jessica" , 34)])
print("\noriginal matrix: ", data_scientists)


original matrix:  [['Charles' '18']
 ['Logan' '20']
 ['Jessica' '34']]


In [49]:
data_scientists = np.array([("Charles", 18),("Logan", 20),("Jessica" , 34)])
print("\noTranspose: ",np.transpose (data_scientists))


oTranspose:  [['Charles' 'Logan' 'Jessica']
 ['18' '20' '34']]


In [53]:
age = np.array([19,20,22,30,40])
weight = np.array([73,45,68,19,30])
employees = np.concatenate([age,weight])
print("concatenate array: ",employees)

concatenate array:  [19 20 22 30 40 73 45 68 19 30]


In [57]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print('Before Reshaping =',arr)

Before Reshaping = [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print('After Reshaping =\n',newarr)

After Reshaping =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [75]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print('Before Reshaping =',arr)
print('After Reshaping =\n',newarr)

Before Reshaping = [ 1  2  3  4  5  6  7  8  9 10 11 12]
After Reshaping =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [77]:
a =np.array([5,6,96,36,8,3])
np.vstack(a)

array([[ 5],
       [ 6],
       [96],
       [36],
       [ 8],
       [ 3]])

In [9]:
import matplotlib.pyplot as plt

im = plt.imread("cat.png")
plt.imshow(im) 

FileNotFoundError: [Errno 2] No such file or directory: 'cat.png'